#!/usr/bin/env bash
# ; -*- mode: sh;-*-

# 1) Byte compile
emacs --batch -f batch-byte-compile *.el

# 2) Make autoloads
emacs --batch --eval='(progn (setq make-backup-files nil) (make-directory-autoloads default-directory "zuul-autoloads.el"))'

# 3) Run tests
emacs --batch --load=zuul.el --load=test/zuul-test.el --funcall=ert-run-tests-batch-and-exit
